In [1]:
import pandas as pd

In [2]:
students = pd.DataFrame({
"Student_ID": [1, 2, 3, 4],
"Student_Name": ["Abel", "Sara", "John", "Helen"]
})
students

   Student_ID Student_Name
0           1         Abel
1           2         Sara
2           3         John
3           4        Helen

In [3]:
enrollments = pd.DataFrame({
"Student_ID": [1, 2, 5],
"Course": ["Python", "SQL", "Machine Learning"]
})
enrollments

   Student_ID            Course
0           1            Python
1           2               SQL
2           5  Machine Learning

In [7]:
# inner join
inner=pd.merge(
    students,
    enrollments,
    on="Student_ID",
    how="inner"
)
inner

   Student_ID Student_Name  Course
0           1         Abel  Python
1           2         Sara     SQL

In [8]:
# left join
left=pd.merge(
    students,
    enrollments,
    on="Student_ID",
    how="left"
)
left

   Student_ID Student_Name  Course
0           1         Abel  Python
1           2         Sara     SQL
2           3         John     NaN
3           4        Helen     NaN

In [9]:
# right join
right=pd.merge(
    students,
    enrollments,
    on="Student_ID",
    how="right"
)
right

   Student_ID Student_Name            Course
0           1         Abel            Python
1           2         Sara               SQL
2           5          NaN  Machine Learning

In [10]:
# outer join
outer=pd.merge(
    students,
    enrollments,
    on="Student_ID",
    how="outer"
)
outer

   Student_ID Student_Name            Course
0           1         Abel            Python
1           2         Sara               SQL
2           3         John               NaN
3           4        Helen               NaN
4           5          NaN  Machine Learning